import { CommonModule } from '@angular/common';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { debounceTime, distinctUntilChanged, finalize } from 'rxjs';
import { ApiError } from '../../core/api/api-error';
import { ApplicationWorkflow } from '../../core/day-hospital/application-workflow.models';
import { ApplicationWorkflowService } from '../../core/day-hospital/application-workflow.service';

interface User { id:string; displayName:string; }
@Component({selector:'app-administration-queue-page',imports:[CommonModule,ReactiveFormsModule],templateUrl:'./administration-queue-page.component.html',styleUrl:'./administration-queue-page.component.scss'})
export class AdministrationQueuePageComponent {
 private readonly workflows=inject(ApplicationWorkflowService);private readonly destroyRef=inject(DestroyRef);
 readonly date=new FormControl(this.today(),{nonNullable:true});readonly search=new FormControl('',{nonNullable:true});readonly filter=new FormControl('all',{nonNullable:true});readonly items=signal<ApplicationWorkflow[]>([]);readonly selected=signal<ApplicationWorkflow|null>(null);readonly users=signal<User[]>([]);readonly loading=signal(false);readonly detailLoading=signal(false);readonly actionLoading=signal(false);readonly error=signal<string|null>(null);readonly actionError=signal<string|null>(null);
 readonly form=new FormGroup({patientVerified:new FormControl(false,{nonNullable:true}),labelVerified:new FormControl(false,{nonNullable:true}),doubleCheckBy:new FormControl('',{nonNullable:true}),startedAt:new FormControl('',{nonNullable:true}),startNotes:new FormControl('',{nonNullable:true}),actualDose:new FormControl('',{nonNullable:true}),completedAt:new FormControl('',{nonNullable:true}),reactionOccurred:new FormControl(false,{nonNullable:true}),reactionDescription:new FormControl('',{nonNullable:true}),observation:new FormControl('',{nonNullable:true}),interruptedAt:new FormControl('',{nonNullable:true}),interruptionReason:new FormControl('',{nonNullable:true}),interruptionDose:new FormControl('',{nonNullable:true}),interruptionMeasures:new FormControl('',{nonNullable:true}),interruptionCondition:new FormControl('',{nonNullable:true}),interruptionDisposition:new FormControl('',{nonNullable:true}),resolutionNotes:new FormControl('',{nonNullable:true}),resolutionCondition:new FormControl('',{nonNullable:true}),resolutionDose:new FormControl('',{nonNullable:true})});
 constructor(){this.search.valueChanges.pipe(debounceTime(280),distinctUntilChanged(),takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.load());this.date.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.load());this.load();}
 load(){this.loading.set(true);this.error.set(null);this.workflows.list('administration',this.date.value,this.search.value.trim()).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>this.items.set((r.items??[]).filter(i=>this.matches(i))),error:e=>this.error.set(ApiError.from(e).message)});}
 open(item:ApplicationWorkflow){this.detailLoading.set(true);this.actionError.set(null);this.workflows.get(item).pipe(finalize(()=>this.detailLoading.set(false))).subscribe({next:r=>{this.selected.set(r.workflow);this.fill(r.workflow);this.loadUsers();},error:e=>this.actionError.set(ApiError.from(e).message)});}
 close(){this.selected.set(null);this.actionError.set(null);} state(item:ApplicationWorkflow){const s=String(item['administrationStatus']??'not_started');const d=item['administrationData'] as Record<string,unknown>|undefined;if(['completed','finished'].includes(s))return'completed';if(s==='withheld'&&d?.['interruptionPending'])return'interrupted';if(s==='withheld')return'terminated';if(['in_progress','in-progress','started'].includes(s))return'active';if(['released','ready'].includes(String(item['preparationStatus']??'')))return'ready';return'waiting';}label(item:ApplicationWorkflow){return({waiting:'Esperando',ready:'Lista para administrar',active:'En administracion',interrupted:'Interrumpida',terminated:'Cerrada sin completar',completed:'Finalizada'})[this.state(item)];}
 start(){const i=this.selected(),v=this.form.getRawValue();if(!i)return;if(!v.patientVerified||!v.labelVerified||!v.doubleCheckBy){this.actionError.set('Confirme paciente, etiqueta y segundo profesional antes de iniciar.');return;}this.act(this.workflows.administrationStart(i,{patientVerified:true,labelVerified:true,doubleCheckBy:v.doubleCheckBy,startedAt:this.iso(v.startedAt),notes:v.startNotes}));}
 complete(){const i=this.selected(),v=this.form.getRawValue();if(!i)return;if(v.actualDose.trim().length<2||v.observation.trim().length<3||v.reactionOccurred&&!v.reactionDescription.trim()){this.actionError.set('Registre dosis real, condicion al cierre y la descripcion de toda reaccion.');return;}this.act(this.workflows.administrationComplete(i,{completedAt:this.iso(v.completedAt),actualDose:v.actualDose,reactionOccurred:v.reactionOccurred,reactionDescription:v.reactionDescription,observation:v.observation}));}
 interrupt(){const i=this.selected(),v=this.form.getRawValue();if(!i)return;if([v.interruptionReason,v.interruptionDose,v.interruptionMeasures,v.interruptionCondition,v.interruptionDisposition].some(x=>x.trim().length<3)){this.actionError.set('Documente motivo, dosis, medidas, condicion y destino clinico antes de interrumpir.');return;}this.act(this.workflows.administrationInterrupt(i,{interruptedAt:this.iso(v.interruptedAt),reason:v.interruptionReason,actualDose:v.interruptionDose,measures:v.interruptionMeasures,patientCondition:v.interruptionCondition,disposition:v.interruptionDisposition}));}
 resolve(decision:'resume'|'terminate'){const i=this.selected(),v=this.form.getRawValue();if(!i)return;if(v.resolutionNotes.trim().length<3||v.resolutionCondition.trim().length<3||(decision==='terminate'&&v.resolutionDose.trim().length<2)){this.actionError.set('Documente la decision y condicion; para cierre, informe la dosis total.');return;}this.act(this.workflows.administrationResolve(i,{resolvedAt:new Date().toISOString(),decision,notes:v.resolutionNotes,actualDose:v.resolutionDose,patientCondition:v.resolutionCondition}));}
 track(_:number,i:ApplicationWorkflow){return`${i.patientId}-${i.treatmentId}-${i.cycleNumber}-${i.applicationDay}`;} time(v:unknown){const d=new Date(String(v??''));return Number.isNaN(d.getTime())?'Sin turno':new Intl.DateTimeFormat('es-AR',{hour:'2-digit',minute:'2-digit'}).format(d);}
 private act(operation:ReturnType<ApplicationWorkflowService['administrationStart']>){this.actionLoading.set(true);this.actionError.set(null);operation.pipe(finalize(()=>this.actionLoading.set(false))).subscribe({next:r=>{this.selected.set(r.workflow);this.items.update(xs=>xs.map(x=>this.same(x,r.workflow)?r.workflow:x));this.fill(r.workflow);},error:e=>this.actionError.set(ApiError.from(e).message)});}
 private fill(item:ApplicationWorkflow){const d=item['administrationData'] as Record<string,unknown>|undefined;const t=(x:unknown)=>x==null?'':String(x);this.form.patchValue({patientVerified:d?.['patientVerified']===true,labelVerified:d?.['labelVerified']===true,doubleCheckBy:t(d?.['doubleCheckByUserId']),startedAt:this.local(d?.['startedAt']),startNotes:t(d?.['notes']),actualDose:t(d?.['actualDose']),completedAt:this.local(d?.['completedAt']),reactionOccurred:d?.['reactionOccurred']===true,reactionDescription:t(d?.['reactionDescription']),observation:t(d?.['observation']),interruptedAt:this.local(d?.['interruptedAt']),interruptionReason:t(d?.['interruptionReason']),interruptionDose:t(d?.['actualDoseAtInterruption']),interruptionMeasures:t(d?.['interruptionMeasures']),interruptionCondition:t(d?.['interruptionPatientCondition']),interruptionDisposition:t(d?.['interruptionDisposition']),resolutionNotes:t(d?.['interruptionResolutionNotes']),resolutionCondition:t(d?.['interruptionResolutionPatientCondition']),resolutionDose:t(d?.['actualDose'])});}
 private loadUsers(){if(this.users().length)return;this.workflows.administrationUsers().subscribe({next:r=>this.users.set((r.items??[]).filter(u=>u.active!==false).map(u=>({id:String(u.id??u.userId??u.username??''),displayName:u.displayName??u.username??'Profesional'})).filter(u=>u.id)),error:()=>this.actionError.set('No se pudieron cargar los profesionales habilitados.')});}private matches(i:ApplicationWorkflow){const f=this.filter.value,s=this.state(i);return f==='all'||f===s;}private same(a:ApplicationWorkflow,b:ApplicationWorkflow){return a.patientId===b.patientId&&a.treatmentId===b.treatmentId&&a.cycleNumber===b.cycleNumber&&a.applicationDay===b.applicationDay;}private iso(v:string){return v?new Date(`${v}:00-03:00`).toISOString():null;}private local(v:unknown){const d=new Date(String(v??''));if(Number.isNaN(d.getTime()))return'';d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);}private today(){return new Date().toLocaleDateString('en-CA',{timeZone:'America/Argentina/Buenos_Aires'});}
}
