import { CommonModule } from '@angular/common';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormArray, FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { debounceTime, distinctUntilChanged, finalize } from 'rxjs';
import { ApiError } from '../../core/api/api-error';
import { ApplicationWorkflow, ApplicationWorkflowDrug } from '../../core/day-hospital/application-workflow.models';
import { ApplicationWorkflowService } from '../../core/day-hospital/application-workflow.service';

interface UserOption { id: string; displayName: string; }

@Component({ selector: 'app-preparation-queue-page', imports: [CommonModule, ReactiveFormsModule], templateUrl: './preparation-queue-page.component.html', styleUrl: './preparation-queue-page.component.scss' })
export class PreparationQueuePageComponent {
  private readonly workflows = inject(ApplicationWorkflowService); private readonly destroyRef = inject(DestroyRef);
  readonly search = new FormControl('', { nonNullable: true }); readonly filter = new FormControl('all', { nonNullable: true });
  readonly items = signal<ApplicationWorkflow[]>([]); readonly selected = signal<ApplicationWorkflow | null>(null); readonly users = signal<UserOption[]>([]);
  readonly loading = signal(false); readonly detailLoading = signal(false); readonly actionLoading = signal(false); readonly error = signal<string | null>(null); readonly actionError = signal<string | null>(null);
  readonly form = new FormGroup({ verifiedBy: new FormControl('', { nonNullable: true }), notes: new FormControl('', { nonNullable: true }), preparations: new FormArray<FormGroup>([]) });
  get preparations(): FormArray<FormGroup> { return this.form.controls.preparations; }
  constructor() { this.search.valueChanges.pipe(debounceTime(280), distinctUntilChanged(), takeUntilDestroyed(this.destroyRef)).subscribe(() => this.load()); this.load(); }
  load(): void { this.loading.set(true); this.error.set(null); this.workflows.list('preparation', '', this.search.value.trim()).pipe(finalize(() => this.loading.set(false))).subscribe({ next: r => this.items.set((r.items ?? []).filter(i => this.matches(i))), error: e => this.error.set(ApiError.from(e).message) }); }
  open(item: ApplicationWorkflow): void { this.detailLoading.set(true); this.actionError.set(null); this.workflows.get(item).pipe(finalize(() => this.detailLoading.set(false))).subscribe({ next: r => { this.selected.set(r.workflow); this.fill(r.workflow); this.loadUsers(); }, error: e => this.actionError.set(ApiError.from(e).message) }); }
  close(): void { this.selected.set(null); this.actionError.set(null); }
  start(): void { const item = this.selected(); if (!item) return; this.act(this.workflows.preparationStart(item, this.form.controls.notes.value)); }
  complete(): void { const item = this.selected(); if (!item || this.actionLoading()) return; if (!this.form.controls.verifiedBy.value) { this.actionError.set('Seleccione el segundo profesional que verifico la mezcla.'); return; } const required = ['lot','expiryDate','quantity','unit','diluent','finalVolume','concentration','ttlMinutes']; if (this.preparations.controls.some(c => required.some(name => !String(c.get(name)?.value ?? '').trim()))) { this.actionError.set('Complete lote, vencimiento, cantidad, unidad, diluyente, volumen, concentracion y TTL para cada droga.'); return; } const preparations = this.preparations.getRawValue().map(p => ({ ...p, quantity: Number(p['quantity']), ttlMinutes: Number(p['ttlMinutes']), inventoryLotId: p['inventoryLotId'] ? Number(p['inventoryLotId']) : null })); this.act(this.workflows.preparationComplete(item, { verifiedBy: this.form.controls.verifiedBy.value, notes: this.form.controls.notes.value, preparations })); }
  release(): void { const item = this.selected(); if (!item) return; this.act(this.workflows.preparationRelease(item, this.form.controls.notes.value)); }
  state(item: ApplicationWorkflow): string { const s = String(item['preparationStatus'] ?? 'not_started'); if (['prepared','ready','completed'].includes(s)) return 'Lista'; if (['in_preparation','in-progress','started'].includes(s)) return 'En preparacion'; if (['released','delivered'].includes(s)) return 'Liberada'; return 'Por iniciar'; }
  action(item: ApplicationWorkflow): string { const state=this.state(item); return state === 'Por iniciar' ? 'Iniciar preparacion' : state === 'En preparacion' ? 'Registrar mezcla' : state === 'Lista' ? 'Liberar a sala' : 'Ver detalle'; }
  track(_: number, item: ApplicationWorkflow): string { return `${item.patientId}-${item.treatmentId}-${item.cycleNumber}-${item.applicationDay}`; }
  private act(operation: ReturnType<ApplicationWorkflowService['preparationStart']>): void { this.actionLoading.set(true); this.actionError.set(null); operation.pipe(finalize(() => this.actionLoading.set(false))).subscribe({ next: r => { this.selected.set(r.workflow); this.items.update(xs => xs.map(x => this.same(x,r.workflow) ? r.workflow : x)); this.fill(r.workflow); }, error: e => this.actionError.set(ApiError.from(e).message) }); }
  private fill(item: ApplicationWorkflow): void { this.preparations.clear(); const preparationData = item['preparationData'] as Record<string, unknown> | undefined; const records = Array.isArray(preparationData?.['preparations']) ? preparationData?.['preparations'] : []; const drugs = item.applicationDrugs ?? []; drugs.forEach((drug,index) => this.preparations.push(this.row(drug, index, records))); this.form.controls.notes.setValue(String(preparationData?.['notes'] ?? '')); }
  private row(drug: ApplicationWorkflowDrug, index: number, records: unknown): FormGroup { const existing = Array.isArray(records) ? records[index] as Record<string, unknown> : {}; const doseText=String(drug.calculatedDoseText ?? drug.prescribedDoseText ?? ''); const number=doseText.match(/[+-]?\d+(?:[.,]\d+)?/)?.[0]?.replace(',','.') ?? ''; return new FormGroup({ componentKey:new FormControl(String(drug.sourceItemRef ?? drug.componentKey ?? `${drug.drugId ?? this.slug(String(drug.drugName ?? 'droga'))}-${index+1}`),{nonNullable:true}), drugName:new FormControl(String(drug.drugName ?? ''),{nonNullable:true}), lot:new FormControl(String(existing['lot'] ?? ''),{nonNullable:true}), expiryDate:new FormControl(String(existing['expiryDate'] ?? ''),{nonNullable:true}), quantity:new FormControl(String(existing['quantity'] ?? number),{nonNullable:true}), quantityText:new FormControl(String(existing['quantityText'] ?? `${number} ${drug.doseUnit ?? drug.unit ?? ''}`.trim()),{nonNullable:true}), unit:new FormControl(String(existing['unit'] ?? drug.doseUnit ?? drug.unit ?? ''),{nonNullable:true}), diluent:new FormControl(String(existing['diluent'] ?? ''),{nonNullable:true}), finalVolume:new FormControl(String(existing['finalVolume'] ?? ''),{nonNullable:true}), concentration:new FormControl(String(existing['concentration'] ?? ''),{nonNullable:true}), ttlMinutes:new FormControl(String(existing['ttlMinutes'] ?? ''),{nonNullable:true}), reservationId:new FormControl(String(existing['reservationId'] ?? ''),{nonNullable:true}), inventoryLotId:new FormControl(String(existing['inventoryLotId'] ?? ''),{nonNullable:true}) }); }
  private loadUsers(): void { if(this.users().length) return; this.workflows.preparationUsers().subscribe({next:r=>this.users.set((r.items??[]).filter(u=>u.active!==false).map(u=>({id:String(u.id??u.userId??u.username??''),displayName:u.displayName??u.username??'Profesional'})).filter(u=>u.id)),error:()=>this.actionError.set('No se pudieron cargar los profesionales habilitados.')}); }
  private matches(item:ApplicationWorkflow):boolean { const f=this.filter.value; const s=String(item['preparationStatus']??'not_started'); return f==='all'||(f==='ready-to-start'&&!['in_preparation','in-progress','started','ready','completed','prepared','released','delivered'].includes(s))||(f==='in-progress'&&['in_preparation','in-progress','started'].includes(s))||(f==='ready'&&['ready','completed','prepared'].includes(s))||(f==='released'&&['released','delivered'].includes(s)); }
  private same(a:ApplicationWorkflow,b:ApplicationWorkflow):boolean{return a.patientId===b.patientId&&a.treatmentId===b.treatmentId&&a.cycleNumber===b.cycleNumber&&a.applicationDay===b.applicationDay;} private slug(v:string):string{return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'droga';}
}
