import { CommonModule } from '@angular/common';
import { Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { debounceTime, distinctUntilChanged, finalize } from 'rxjs';
import { ApiError } from '../../core/api/api-error';
import { DayHospitalSettings, InfusionAppointment, InfusionCandidate, ScheduleService } from '../../core/day-hospital/schedule.service';

type DragItem={kind:'candidate';value:InfusionCandidate}|{kind:'appointment';value:InfusionAppointment};
@Component({selector:'app-schedule-page',imports:[CommonModule,ReactiveFormsModule],templateUrl:'./schedule-page.component.html',styleUrl:'./schedule-page.component.scss'})
export class SchedulePageComponent {
 private readonly schedules=inject(ScheduleService);private readonly destroyRef=inject(DestroyRef);
 readonly date=new FormControl(this.today(),{nonNullable:true});readonly search=new FormControl('',{nonNullable:true});readonly candidateFilter=new FormControl('all',{nonNullable:true});readonly settings=signal<DayHospitalSettings>({chairCount:6,slotMinutes:10,startTime:'08:00',endTime:'16:00'});readonly appointments=signal<InfusionAppointment[]>([]);readonly candidates=signal<InfusionCandidate[]>([]);readonly drag=signal<DragItem|null>(null);readonly loading=signal(false);readonly error=signal<string|null>(null);readonly actionError=signal<string|null>(null);readonly busy=signal(false);
 readonly chairs=computed(()=>Array.from({length:this.settings().chairCount},(_,i)=>String(i+1)));readonly slots=computed(()=>{const [sh,sm]=this.settings().startTime.split(':').map(Number);const [eh,em]=this.settings().endTime.split(':').map(Number);const out:string[]=[];for(let m=sh*60+sm;m<eh*60+em;m+=this.settings().slotMinutes){out.push(`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`)}return out;});
 readonly visibleCandidates=computed(()=>this.candidates().filter(c=>{const f=this.candidateFilter.value;return f==='all'||f==='eligible'&&(c.prescriptionConfirmed!==false&&c.medicationReady===true)||f==='missing-medication'&&c.medicationReady!==true||f==='missing-prescription'&&c.prescriptionConfirmed===false;}));
 constructor(){this.date.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.load());this.search.valueChanges.pipe(debounceTime(280),distinctUntilChanged(),takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.loadCandidates());this.load();}
 load(){this.loading.set(true);this.error.set(null);this.schedules.settings().subscribe({next:r=>{const d=r.items?.find(x=>x.definition)?.definition??{};this.settings.set({chairCount:this.valid(Number(d.chairCount),6),slotMinutes:[5,10,15,20,30].includes(Number(d.slotMinutes))?Number(d.slotMinutes):10,startTime:d.startTime||'08:00',endTime:d.endTime||'16:00'});},error:()=>{}});this.schedules.appointments(this.date.value).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>this.appointments.set(r.infusions??[]),error:e=>this.error.set(ApiError.from(e).message)});this.loadCandidates();}
 loadCandidates(){this.schedules.candidates(this.search.value.trim()).subscribe({next:r=>this.candidates.set(r.candidates??[]),error:e=>this.error.set(ApiError.from(e).message)});}
 starts(item:InfusionAppointment,chair:string,time:string){return String(item.chair)===chair&&this.time(item.scheduledAt)===time;} appointmentAt(chair:string,time:string){return this.appointments().find(a=>this.starts(a,chair,time));} occupied(chair:string,time:string){const at=this.slotDate(time).getTime();return this.appointments().find(a=>{if(String(a.chair)!==chair)return false;const start=new Date(a.scheduledAt).getTime();const end=start+Math.ceil(a.durationMinutes/this.settings().slotMinutes)*this.settings().slotMinutes*60000;return at>=start&&at<end;});}
 beginCandidate(candidate:InfusionCandidate){if(this.canDrag(candidate))this.drag.set({kind:'candidate',value:candidate});}beginAppointment(item:InfusionAppointment){this.drag.set({kind:'appointment',value:item});}endDrag(){this.drag.set(null);}drop(event:DragEvent,chair:string,time:string){event.preventDefault();const item=this.drag();if(!item||this.busy())return;const at=this.slotDate(time);if(this.occupied(chair,time)&&!(item.kind==='appointment'&&this.occupied(chair,time)?.id===item.value.id)){this.actionError.set('Ese espacio ya está ocupado. El sistema no permite superponer turnos.');return;}this.busy.set(true);this.actionError.set(null);const target=at.toISOString();const action=item.kind==='candidate'?this.schedules.create(item.value,target,chair):this.schedules.move(item.value,target,chair);action.pipe(finalize(()=>{this.busy.set(false);this.drag.set(null);})).subscribe({next:()=>{this.load();},error:e=>this.actionError.set(ApiError.from(e).message)});}
 remove(item:InfusionAppointment){if(this.busy())return;this.busy.set(true);this.schedules.cancel(item).pipe(finalize(()=>this.busy.set(false))).subscribe({next:()=>this.load(),error:e=>this.actionError.set(ApiError.from(e).message)});}
 canDrag(c:InfusionCandidate){return !c.blockedReason&&c.prescriptionConfirmed!==false&&c.medicationReady===true;}slotClass(chair:string,time:string){const o=this.occupied(chair,time);return o?'occupied':'';}duration(item:InfusionAppointment){return `${item.durationMinutes>=60?`${Math.floor(item.durationMinutes/60)} h ${item.durationMinutes%60||''}`:`${item.durationMinutes} min`}`.trim();}time(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Argentina/Buenos_Aires'}).format(d);}track(_:number,x:{id?:string;patientId?:string;treatmentId?:string;cycleNumber?:number;applicationDay?:number}){return x.id??`${x.patientId}-${x.treatmentId}-${x.cycleNumber}-${x.applicationDay}`;}
 private slotDate(time:string){return new Date(`${this.date.value}T${time}:00-03:00`);}private valid(v:number,f:number){return Number.isInteger(v)&&v>0&&v<=200?v:f;}private today(){return new Date().toLocaleDateString('en-CA',{timeZone:'America/Argentina/Buenos_Aires'});}
}
