import { CommonModule } from '@angular/common';
import { Component, DestroyRef, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { debounceTime, distinctUntilChanged, finalize } from 'rxjs';
import { ApiClientService } from '../../core/api/api-client.service'; import { ApiError } from '../../core/api/api-error';
interface Protocol {id:string;name:string;description?:string;category?:string;cycleDays?:number;durationMinutes?:number;durationText?:string;catalogOnly?:boolean;active?:boolean;componentCount?:number;components?:Array<Record<string,unknown>>;[key:string]:unknown}
@Component({selector:'app-protocols-page',imports:[CommonModule,ReactiveFormsModule,RouterLink],templateUrl:'./protocols-page.component.html',styleUrl:'./protocols-page.component.scss'})
export class ProtocolsPageComponent {private readonly api=inject(ApiClientService);private readonly destroyRef=inject(DestroyRef);readonly search=new FormControl('',{nonNullable:true});readonly items=signal<Protocol[]>([]);readonly selected=signal<Protocol|null>(null);readonly loading=signal(false);readonly detailLoading=signal(false);readonly error=signal<string|null>(null);constructor(){this.search.valueChanges.pipe(debounceTime(250),distinctUntilChanged(),takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.load());this.load();}load(){this.loading.set(true);this.error.set(null);this.api.get<{protocols?:Protocol[]}>('/api/clinical/protocols',{includeCatalog:1}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{const q=this.normalize(this.search.value);this.items.set((r.protocols??[]).filter(x=>!q||this.normalize(`${x.name} ${x.description??''} ${x.category??''}`).includes(q)));},error:e=>this.error.set(ApiError.from(e).message)});}open(item:Protocol){this.detailLoading.set(true);this.api.get<{protocol:Protocol}>(`/api/clinical/protocols/${encodeURIComponent(item.id)}`).pipe(finalize(()=>this.detailLoading.set(false))).subscribe({next:r=>this.selected.set(r.protocol),error:e=>this.error.set(ApiError.from(e).message)});}close(){this.selected.set(null);}track(_:number,x:Protocol){return x.id;}private normalize(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}}
